repos:
  # - repo: https://github.com/norwoodj/helm-docs
  #   rev: v1.2.0
  #   hooks:
  #     - id: helm-docs
  #       args:
  #         # Make the tool search for charts only under the `charts` directory
  #         - --chart-search-root=charts

  #         # The `./` makes it relative to the chart-search-root set above
  #         - --template-files=./_templates.gotmpl

  #         # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
  #         # A base filename makes it relative to each chart directory found
  #         - --template-files=README.md.gotmpl
  - repo: https://github.com/rapidsai/frigate
    rev: v0.6.0a #  pre-commit autoupdate  - to keep the version up to date
    hooks:
      - id: frigate
        args:
          - --output=README.rst
          - --format=rst
          - --no-credits
          - --no-deps